import { Github, Wand2 } from 'lucide-react'
import { Button } from './components/ui/button';
import { Separator } from './components/ui/separator';
import { Textarea } from './components/ui/textarea';
import { Label } from './components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './components/ui/select';
import { Slider } from './components/ui/slider';
import { VideoInputForm } from './components/video-imput-form';
import { PromptSelect } from './components/prompt-select';
import { useState } from 'react';
import { useCompletion } from 'ai/react'

export function App() {
  const [temperature, setTemperature] = useState(0.5)
  const [videoId, setvVdeoId] = useState<string | null>(null)

  
  const { input, setInput, handleInputChange, handleSubmit, completion, isLoading } = useCompletion({
    api: 'http://localhost:3333/ai/complete',
    body: {
      videoId,
      temperature,
    },
    headers: {
      'Content-Type': 'application/json',
    }
  })

  return (
    <div className='flex flex-col min-h-screen'>
      <div className='flex items-center justify-between px-6 py-3 border-b'>
        <h1 className='text-xl font-bold'>upload.ai</h1>

        <div className='flex items-center gap-3'>
          <span className='text-sm text-muted-foreground'>Made with 🤍 by Gabriel Carvalho.</span>
          <Separator orientation='vertical' className='h-6' />
          <Button variant='outline'>
            <Github className='w-4 h-4 mr-2'/>
            Github
          </Button>
        </div>
      </div>

      <main className='flex flex-1 gap-6 p-6'>
        <div className='flex flex-col flex-1 gap-4'>
          <div className='grid flex-1 grid-rows-2 gap-4'>
            <Textarea
              className='p-4 leading-relaxed resize-none'
              placeholder='Add the prompt here for the AI...'
              value={input}
              onChange={handleInputChange}
            />
            <Textarea
              className='p-4 leading-relaxed resize-none'
              placeholder='Result generated by AI...'
              readOnly
              value={completion}
            />
          </div>

          <p className='text-sm text-muted-foreground'>
            Remind: You can utilize the variable <code className='text-emerald-400'>{'{transcription}'}</code> on your prompt to add the selected video transcription content
          </p>
        </div>

        <aside className='space-y-6 w-80'>
          <VideoInputForm onVideoUploaded={setvVdeoId} />

          <Separator />

          <form onSubmit={handleSubmit} className='space-y-6'>
            <div className='space-y-2'>
              <Label>Prompt</Label>
              <PromptSelect onPromptSelect={setInput} />
            </div>

            <div className='space-y-2'>
              <Label>Model</Label>

              <Select disabled defaultValue='gpt3.5-turbo'>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value='gpt3.5-turbo'>GPT 3.5-turbo 16k</SelectItem>
                </SelectContent>
              </Select>
              <span className='block text-xs italic text-muted-foreground'>You will be able to customize this option soon</span>
            </div>

            <Separator />

            <div className='space-y-4'>
              <Label>Temperature</Label>
              
              <Slider
                min={0}
                max={1}
                step={0.1}
                value={[temperature]}
                onValueChange={value => setTemperature(value[0])}
              />
              
              <span className='block text-xs italic leading-relaxed text-muted-foreground'>Higher values tend to return more creative results, but with possible errors.</span>
            </div>

            <Separator />

            <Button disabled={isLoading} type='submit' className='w-full'>
              Run
              <Wand2 className='w-4 h-4 ml-2' />
            </Button>
          </form>
        </aside>
      </main>
    </div>
  )
}
